---
language: python
dist: trusty
sudo: required

python: 3.5

git:
  depth: 1

before_install:
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get update
  - sudo apt-get install -y nodejs

script:
  - set -e
  - echo y | ./scripts/test.sh
